---
- name: Create a VIP, pool and pool members
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    provider:
      server: 10.18.190.121
      user: admin
      password: admin
      validate_certs: no
      server_port: 443

# Add a Pool
  tasks:
    - name: Create a monitor
      bigip_monitor_gateway_icmp:
        provider: "{{ provider }}"
        name: gw1
        adaptive: no
        interval: 1
        time_until_up: 0
        timeout: 3
      delegate_to: localhost

    - name: Create a Pool
      bigip_pool:
        provider: "{{provider}}"
        lb_method: ratio-member
        name: web-pool
        slow_ramp_time: 120
        monitor_type: and_list
        monitors:
          - http
          - gw1
      delegate_to: localhost

    - name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: web-pool
        port: 80
      with_items:
       - host: 100.100.100.2
         name: web01
       - host: 100.100.100.3
         name: web02
      delegate_to: localhost

    - name: Create a VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: foo-vip
        destination: 192.168.30.101
        name: vip-1
        pool: web-pool
        port: '80'
        snat: Automap
        profiles:
          - http
      delegate_to: localhost

    - name: Create a trunk on hardware
      bigip_trunk:
        provider: "{{ provider }}"
        name: trunk1
        interfaces:
          - 2.1
          - 2.2
        link_selection_policy: maximum-bandwidth
        frame_distribution_hash: destination-mac
        lacp_enabled: yes
        lacp_mode: passive
        lacp_timeout: short
      delegate_to: localhost

    - name: Create VLAN
      bigip_vlan:
        tagged_interface: trunk1
        name: vlan100
        tag: 100
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Create VLAN
      bigip_vlan:
        tagged_interface: trunk1
        name: vlan30
        tag: 30
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Create Self IP
      bigip_selfip:
        address: 192.168.30.100
        name: selfIPClient
        netmask: 255.255.255.0
        vlan: vlan30
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Create Self IP
      bigip_selfip:
        address: 100.100.100.100
        name: selfIPWebServer
        netmask: 255.255.255.0
        vlan: vlan100
        provider: "{{ provider }}"
      delegate_to: localhost
